# Generated by Django 3.2.25 on 2025-01-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=35)),
                ('third_name', models.CharField(max_length=35)),
                ('genders', models.CharField(max_length=35)),
                ('bithday', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=8)),
                ('email', models.CharField(max_length=35)),
                ('professia', models.CharField(max_length=35)),
                ('obrazovaniy', models.CharField(max_length=35)),
                ('dostyshenia', models.CharField(max_length=100)),
            ],
        ),
    ]
