# Generated by Django 3.2.25 on 2025-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_student_bithday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olimpiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(max_length=35)),
            ],
        ),
    ]
