# Generated by Django 3.2.25 on 2025-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_olimpiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passoword',
            field=models.CharField(default=1234, max_length=35),
            preserve_default=False,
        ),
    ]
