# Generated by Django 3.2.25 on 2025-01-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_passoword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passoword',
            field=models.CharField(default=1234, max_length=35),
        ),
    ]
