# Generated by Django 3.2.25 on 2025-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_student_passoword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passoword',
        ),
        migrations.AddField(
            model_name='student',
            name='passsoword',
            field=models.CharField(default=1234, max_length=35),
        ),
    ]
