# Generated by Django 3.2.25 on 2025-01-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20250125_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passsoword',
        ),
    ]
