# Generated by Django 3.2.25 on 2025-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_student_passsoword'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passoword',
            field=models.CharField(default=1234, max_length=35),
        ),
    ]
