# Generated by Django 3.2.25 on 2025-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_student_passoword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dostyshenia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
