# Generated by Django 3.2.25 on 2025-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_student_dostyshenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dostyshenia_win',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dostyshenia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
