# Generated by Django 3.2.25 on 2025-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20250125_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimpiad',
            name='kolvo',
            field=models.IntegerField(default=12900),
        ),
    ]
