# Generated by Django 3.2.25 on 2025-01-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_olimpiad_kolvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dostyshenia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='dostyshenia_win',
            field=models.CharField(default='', max_length=100),
        ),
    ]
