# Generated by Django 3.2.25 on 2025-01-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20250126_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=35)),
                ('telega', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='telega',
            field=models.CharField(default='', max_length=35),
        ),
    ]
