# Generated by Django 3.2.25 on 2025-01-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20250126_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='metka',
            field=models.BooleanField(default=False),
        ),
    ]
