# Generated by Django 3.2.25 on 2025-01-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_company_metka'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sorev',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
