# Generated by Django 3.2.25 on 2025-01-26 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_student_sorev'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimpiad',
            name='vrem',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
